Jonnitto:
  PrettyEmbedVimeo:
    url:
      embed: 'https://player.vimeo.com/video/%id%'
      href: 'https://vimeo.com/%id%'
    defaults:
      # Should the video be opened on a lightbox? Per default this is set via the node properties
      lightbox: false
      # When the lightbox is set, should the preview image preserve his aspect ratio?  default this is set via the node properties
      preserveAspectRatio: true
      # Whether to pause the current video when another Vimeo video on the same page starts to play.
      # Set this value to false to permit simultaneous playback of all the videos on the page.
      autopause: true
      # Whether the player is in background mode, which hides the playback controls, enables autoplay, and loops the video.
      background: false
      # Whether to restart the video automatically after reaching the end.
      loop: false
      # Whether the video is muted upon loading. The true value is required for the autoplay behavior in some browsers.
      muted: false
      # Whether the video plays inline on supported mobile devices.
      # Note that if set to false it does not imply that the video will always be played in fullscreen.
      playsinline: true
      # Whether the responsive player and transparent background are enabled
      transparent: true
      allowFullScreen: true
      # The hexadecimal color value of the playback controls, which is normally 00ADEF.
      color: false
      # Whether the player displays the title overlay
      previewTitle: false
      # Whether to display the video owner's name.
      previewByline: false
      # Whether to display the video owner's portrait.
      previewPortrait: false
